version: '3.8'

services:
  frontend:
    build:
      context: ./link-shortener
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back_files
      dockerfile: Dockerfile
    ports:
      - "9000:9000"